### ISSUE TITLE
Code review of branch 'code review'

### ISSUE THREAD

**Issue by emilyherrett** [opensafely/lone_households#2]
Not sure whether you'll be able to review the branch now?
https://github.com/opensafely/lone_households/tree/Code-review

**Comment by hjforbes** [comment]
This looks great.  COmments are minor, and might reflect my lack of experience with the measures function you're using

1. I initially wondered if you needed to include children in the household definition – to work out household size.  However, there is the function (households_as_of) for that.  Does that variable definitely include children?
2.	The index date in the study definition is 1st January 2018, but protocol says start follow-up 1st March 2018.  Is that because you want three months registration prior to 1st March 2018?
3.	For each month are we extracting a different cohort?  Does that mean that the study population will be all those registered on 1st of that month? Or is it all those registered on 1st March 2018… Just need to make that clear in the protocol. 
4.	In protocol, we require individuals to be registered between 1st March 2018 and 31st January 2022.  Individuals may drop out after 1stFeb 2020, if they die or transfer out of the practice.  So perhaps the analysis pop is those registered 1st March 2018 and 1st Feb 2020?
5.	In the protocol it says, “diagnoses, symptoms, or hospital attendances that occur within 7 days of each other represent the same event”. Is this if a depression diagnosis is made (say 31st July, and then again 4th August, it would only get count in the July numerator?  Not sure how this gets implemented in the study definition.  Could just cut from the protocol?
6.	In the sensitivity analysis section you have something on SSRIs as an outcome – I don’t think this is in the study definition at the moment. 

Let me know if any of that is unclear!
